In [1]:
import os
import pickle
import pandas as pd
import numpy as np

# Dataset path
pkl_path = "/kaggle/input/datasets/esayasmelaku/machine-learning-flare-dataset/ARTop_Processed_Regions (1).pkl"

# Check file
print("Exists:", os.path.exists(pkl_path))

if os.path.exists(pkl_path):
    print("Size:", round(os.path.getsize(pkl_path) / (1024**2), 2), "MB")

# Load dataset
with open(pkl_path, "rb") as f:
    data = pickle.load(f)

print("Dataset type:", type(data))
print("Number of Active Regions:", len(data))

Exists: True
Size: 76.46 MB
Dataset type: <class 'dict'>
Number of Active Regions: 244

In [2]:
# Look at the first Active Region
ar_id = list(data.keys())[0]

print("Example AR ID:", ar_id)
print("Available data:", data[ar_id].keys())

Example AR ID: 8
Available data: dict_keys(['series', 'integrated', 'kurtosis', 'flares', 'limb'])

In [3]:
df = data[ar_id]["series"]

print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
display(df.head())

Shape: (598, 13)

Columns:
['times(seconds)', 'bz', 'vz', 'sz', 'dL', 'dH', 'vz_dL_pos', 'vz_dH_pos', 'vzbz', 'flare6hr', 'flare12hr', 'flare24hr', 'flare48hr']

First 5 rows:

,times(seconds),bz,vz,sz,dL,dH,vz_dL_pos,vz_dH_pos,vzbz,flare6hr,flare12hr,flare24hr,flare48hr
0,0.0,-7.261643e+10,-2.538568e+07,1.818693e+11,2.526069e+12,2.608061e+15,-6.692624e+09,-4.094099e+13,-1.675118e+09,0.0,0.0,0.0,0.0
1,0.2,-7.502907e+10,-5.500223e+07,1.154204e+11,5.581750e+12,2.158485e+15,-1.064073e+10,-8.097001e+12,-2.587148e+09,0.0,0.0,0.0,0.0
2,0.4,-8.852978e+10,-2.877874e+07,3.328066e+11,1.444057e+12,3.466406e+15,6.462528e+09,-4.868059e+13,-1.047355e+09,0.0,0.0,0.0,0.0
3,0.6,-9.159094e+10,-3.965101e+07,-9.764858e+10,3.706723e+12,7.004260e+15,7.050973e+09,-7.940836e+13,-2.718113e+09,0.0,0.0,0.0,0.0
4,0.8,-8.323025e+10,-7.355947e+07,-7.661304e+10,1.598462e+12,5.223380e+14,-9.579989e+09,3.952987e+12,-3.452363e+09,0.0,0.0,0.0,0.0

In [4]:
import os
import pickle
import numpy as np
import pandas as pd

pkl_path = "/kaggle/input/datasets/esayasmelaku/machine-learning-flare-dataset/ARTop_Processed_Regions (1).pkl"

print("File exists:", os.path.exists(pkl_path))

with open(pkl_path, "rb") as f:
    data = pickle.load(f)

print("Dataset type:", type(data))
print("Active regions:", len(data))

File exists: True
Dataset type: <class 'dict'>
Active regions: 244

In [5]:
ar_id = list(data.keys())[0]

print("Example AR ID:", ar_id)
print("Available components:", data[ar_id].keys())

series_df = data[ar_id]["series"]

print("\nSeries shape:", series_df.shape)
print("\nColumns:")
print(series_df.columns.tolist())

display(series_df.head())

Example AR ID: 8
Available components: dict_keys(['series', 'integrated', 'kurtosis', 'flares', 'limb'])

Series shape: (598, 13)

Columns:
['times(seconds)', 'bz', 'vz', 'sz', 'dL', 'dH', 'vz_dL_pos', 'vz_dH_pos', 'vzbz', 'flare6hr', 'flare12hr', 'flare24hr', 'flare48hr']

,times(seconds),bz,vz,sz,dL,dH,vz_dL_pos,vz_dH_pos,vzbz,flare6hr,flare12hr,flare24hr,flare48hr
0,0.0,-7.261643e+10,-2.538568e+07,1.818693e+11,2.526069e+12,2.608061e+15,-6.692624e+09,-4.094099e+13,-1.675118e+09,0.0,0.0,0.0,0.0
1,0.2,-7.502907e+10,-5.500223e+07,1.154204e+11,5.581750e+12,2.158485e+15,-1.064073e+10,-8.097001e+12,-2.587148e+09,0.0,0.0,0.0,0.0
2,0.4,-8.852978e+10,-2.877874e+07,3.328066e+11,1.444057e+12,3.466406e+15,6.462528e+09,-4.868059e+13,-1.047355e+09,0.0,0.0,0.0,0.0
3,0.6,-9.159094e+10,-3.965101e+07,-9.764858e+10,3.706723e+12,7.004260e+15,7.050973e+09,-7.940836e+13,-2.718113e+09,0.0,0.0,0.0,0.0
4,0.8,-8.323025e+10,-7.355947e+07,-7.661304e+10,1.598462e+12,5.223380e+14,-9.579989e+09,3.952987e+12,-3.452363e+09,0.0,0.0,0.0,0.0

In [6]:
observation_counts = {
    ar_id: len(ar_data["series"])
    for ar_id, ar_data in data.items()
}

total_rows = sum(observation_counts.values())

print("Active regions:", len(data))
print("Total time-series observations:", total_rows)

print("\nObservation statistics:")
print(pd.Series(observation_counts).describe())

Active regions: 244
Total time-series observations: 227039

Observation statistics:
count     244.000000
mean      930.487705
std       391.797309
min       116.000000
25%       613.500000
50%       959.000000
75%      1269.500000
max      1681.000000
dtype: float64

In [7]:
column_signatures = {
    tuple(ar_data["series"].columns)
    for ar_data in data.values()
}

print("Number of different column structures:", len(column_signatures))

if len(column_signatures) == 1:
    print("All Active Regions have the same columns.")
else:
    print("WARNING: Different column structures exist.")

Number of different column structures: 1
All Active Regions have the same columns.

In [8]:
quality_rows = []

for ar_id, ar_data in data.items():
    df = ar_data["series"]

    numeric_df = df.select_dtypes(include=np.number)

    quality_rows.append({
        "ar_id": ar_id,
        "n_obs": len(df),
        "n_missing": df.isna().sum().sum(),
        "n_inf": np.isinf(numeric_df).sum().sum(),
        "n_duplicate_rows": df.duplicated().sum()
    })

quality_df = pd.DataFrame(quality_rows)

print("Total missing values:", quality_df["n_missing"].sum())
print("Total infinite values:", quality_df["n_inf"].sum())
print("Total duplicate rows:", quality_df["n_duplicate_rows"].sum())

print("\nARs containing missing values:")
display(
    quality_df[quality_df["n_missing"] > 0]
    .sort_values("n_missing", ascending=False)
)

Total missing values: 33224
Total infinite values: 0
Total duplicate rows: 0

ARs containing missing values:

    ar_id  n_obs  n_missing  n_inf  n_duplicate_rows
63   1209   1559       6128      0                 0
94   2832   1557       5976      0                 0
108  3813   1199       5640      0                 0
118  5298   1559       3896      0                 0
114  4231   1079       3688      0                 0
89   2501   1081       2224      0                 0
85   2191   1437       2216      0                 0
98   3097    480       1992      0                 0
107  3741    480       1464      0                 0

In [9]:
suspect_ars = quality_df.loc[
    quality_df["n_missing"] > 0, "ar_id"
].tolist()

for ar_id in suspect_ars:
    df = data[ar_id]["series"]

    missing_by_column = df.isna().sum()
    missing_by_column = missing_by_column[missing_by_column > 0]

    print(f"\nAR {ar_id} | observations: {len(df)}")
    print(missing_by_column)

AR 1209 | observations: 1559
bz           766
vz           766
sz           766
dL           766
dH           766
vz_dL_pos    766
vz_dH_pos    766
vzbz         766
dtype: int64

AR 2191 | observations: 1437
bz           277
vz           277
sz           277
dL           277
dH           277
vz_dL_pos    277
vz_dH_pos    277
vzbz         277
dtype: int64

AR 2501 | observations: 1081
bz           278
vz           278
sz           278
dL           278
dH           278
vz_dL_pos    278
vz_dH_pos    278
vzbz         278
dtype: int64

AR 2832 | observations: 1557
bz           747
vz           747
sz           747
dL           747
dH           747
vz_dL_pos    747
vz_dH_pos    747
vzbz         747
dtype: int64

AR 3097 | observations: 480
bz           249
vz           249
sz           249
dL           249
dH           249
vz_dL_pos    249
vz_dH_pos    249
vzbz         249
dtype: int64

AR 3741 | observations: 480
bz           183
vz           183
sz           183
dL           183
dH           183
vz_dL_pos    183
vz_dH_pos    183
vzbz         183
dtype: int64

AR 3813 | observations: 1199
bz           705
vz           705
sz           705
dL           705
dH           705
vz_dL_pos    705
vz_dH_pos    705
vzbz         705
dtype: int64

AR 4231 | observations: 1079
bz           461
vz           461
sz           461
dL           461
dH           461
vz_dL_pos    461
vz_dH_pos    461
vzbz         461
dtype: int64

AR 5298 | observations: 1559
bz           487
vz           487
sz           487
dL           487
dH           487
vz_dL_pos    487
vz_dH_pos    487
vzbz         487
dtype: int64

In [10]:
feature_cols = [
    "bz",
    "vz",
    "sz",
    "dL",
    "dH",
    "vz_dL_pos",
    "vz_dH_pos",
    "vzbz"
]

target_cols = [
    "flare6hr",
    "flare12hr",
    "flare24hr",
    "flare48hr"
]

print("Physical features:")
for col in feature_cols:
    print(" -", col)

print("\nFuture flare targets:")
for col in target_cols:
    print(" -", col)

Physical features:
 - bz
 - vz
 - sz
 - dL
 - dH
 - vz_dL_pos
 - vz_dH_pos
 - vzbz

Future flare targets:
 - flare6hr
 - flare12hr
 - flare24hr
 - flare48hr

In [11]:
feature_stats = []

for ar_id, ar_data in data.items():
    df = ar_data["series"]
    
    feature_stats.append(df[feature_cols])

all_features = pd.concat(feature_stats, ignore_index=True)

print("Total observations:", len(all_features))
print("Number of features:", len(feature_cols))

print("\nMissing values:")
display(all_features[feature_cols].isna().sum())

print("\nFeature statistics:")
display(all_features[feature_cols].describe().T)

Total observations: 227039
Number of features: 8

Missing values:

bz           4153
vz           4153
sz           4153
dL           4153
dH           4153
vz_dL_pos    4153
vz_dH_pos    4153
vzbz         4153
dtype: int64

Feature statistics:

,count,mean,std,min,25%,50%,75%,max
bz,222886.0,-3.359538e+10,5.498206e+11,-9.895126e+12,-1.233356e+11,0.000000e+00,7.768488e+10,7.355955e+12
vz,222886.0,-3.210507e+07,6.474751e+08,-2.040074e+10,-6.895228e+07,-5.763638e+06,1.960611e+07,2.887958e+10
sz,222886.0,1.781044e+13,1.771894e+14,-2.253923e+16,0.000000e+00,2.283387e+12,1.731056e+13,1.833382e+16
dL,222886.0,7.573660e+12,9.019968e+13,-5.120923e+15,-2.146189e+12,1.175610e+12,8.939513e+12,7.096411e+15
dH,222886.0,1.238063e+17,1.631252e+18,-3.538714e+19,-1.330011e+15,3.098643e+15,3.044076e+16,1.679086e+20
vz_dL_pos,222886.0,4.231382e+11,1.513534e+14,-1.184381e+16,-2.687899e+10,7.842550e+09,1.781584e+11,6.297883e+16
vz_dH_pos,222886.0,-1.620171e+16,6.193487e+18,-7.985128e+20,-1.081918e+14,2.956907e+13,1.264243e+15,8.416269e+20
vzbz,222886.0,7.270297e+09,7.444743e+10,-5.667021e+12,-1.255672e+09,1.167117e+09,1.075040e+10,4.302108e+12

In [12]:
for target in target_cols:
    values = []

    for ar_data in data.values():
        values.extend(
            ar_data["series"][target].dropna().tolist()
        )

    s = pd.Series(values)

    print("\n" + "=" * 60)
    print(target)
    print("=" * 60)

    print("Count:", len(s))
    print("Minimum:", s.min())
    print("Maximum:", s.max())
    print("Mean:", s.mean())
    print("Median:", s.median())
    print("Unique values:", s.nunique())

    print("\nMost common values:")
    display(s.value_counts().head(20))

============================================================
flare6hr
============================================================
Count: 227039
Minimum: 0.0
Maximum: 1.0
Mean: 0.06378121442359166
Median: 0.0
Unique values: 730

Most common values:

0.000000    195061
0.260348      1379
0.278486       774
0.307612       751
0.269795       745
0.286532       740
0.294023       699
0.301030       670
0.319688       554
0.313818       550
0.345053       539
0.325257       501
0.340432       500
0.372840       442
0.349485       439
0.376287       439
0.382870       429
0.335606       426
0.353743       419
0.361790       384
Name: count, dtype: int64

============================================================
flare12hr
============================================================
Count: 227039
Minimum: 0.0
Maximum: 1.0
Mean: 0.09166726293883644
Median: 0.0
Unique values: 1037

Most common values:

0.000000    183595
0.260348      1673
0.307612       961
0.286532       942
0.269795       934
0.294023       835
0.278486       821
0.301030       776
0.345053       756
0.325257       625
0.313818       589
0.353743       581
0.349485       542
0.382870       540
0.319688       525
0.372840       522
0.369280       517
0.340432       495
0.408367       462
0.403196       445
Name: count, dtype: int64

============================================================
flare24hr
============================================================
Count: 227039
Minimum: 0.0
Maximum: 1.0
Mean: 0.12320736820432349
Median: 0.0
Unique values: 1407

Most common values:

0.000000    172440
0.260348      1675
0.345053      1278
0.286532      1219
0.307612      1219
0.269795       993
0.353743       921
0.294023       750
0.278486       733
0.349485       687
0.301030       637
0.325257       634
0.372840       616
0.369280       577
0.365599       539
0.382870       537
0.403196       511
0.500000       505
0.313818       483
0.357841       440
Name: count, dtype: int64

============================================================
flare48hr
============================================================
Count: 227039
Minimum: 0.0
Maximum: 1.0
Mean: 0.15024823952083635
Median: 0.0
Unique values: 1716

Most common values:

0.000000    164631
0.345053      1808
0.286532      1626
0.260348      1483
0.307612      1418
0.269795      1235
0.353743       702
0.294023       602
0.278486       568
0.301030       560
0.325257       546
0.438969       542
0.382870       533
0.424743       526
0.349485       507
0.449835       501
0.397766       491
0.369280       460
0.365599       456
0.372840       414
Name: count, dtype: int64

In [13]:
flare24_values = []

for ar_data in data.values():
    flare24_values.extend(
        ar_data["series"]["flare24hr"].dropna().tolist()
    )

flare24 = pd.Series(flare24_values)

print("flare24hr observations:", len(flare24))
print("Minimum:", flare24.min())
print("Maximum:", flare24.max())
print("Mean:", flare24.mean())
print("Median:", flare24.median())
print("Unique values:", flare24.nunique())

print("\nTop 30 most common values:")
display(flare24.value_counts().head(30))

flare24hr observations: 227039
Minimum: 0.0
Maximum: 1.0
Mean: 0.12320736820432349
Median: 0.0
Unique values: 1407

Top 30 most common values:

0.000000    172440
0.260348      1675
0.345053      1278
0.286532      1219
0.307612      1219
0.269795       993
0.353743       921
0.294023       750
0.278486       733
0.349485       687
0.301030       637
0.325257       634
0.372840       616
0.369280       577
0.365599       539
0.382870       537
0.403196       511
0.500000       505
0.313818       483
0.357841       440
0.438969       427
0.335606       394
0.379628       387
0.510348       382
0.456519       376
0.376287       363
0.400515       357
0.330555       355
0.435091       351
0.397766       342
Name: count, dtype: int64

In [14]:
tables = []

for ar_id, ar_data in data.items():
    df = ar_data["series"].copy()

    df["ar_id"] = ar_id

    tables.append(df)

combined_df = pd.concat(tables, ignore_index=True)

print("Combined dataset shape:", combined_df.shape)

display(combined_df.head())

Combined dataset shape: (227039, 14)

,times(seconds),bz,vz,sz,dL,dH,vz_dL_pos,vz_dH_pos,vzbz,flare6hr,flare12hr,flare24hr,flare48hr,ar_id
0,0.0,-7.261643e+10,-2.538568e+07,1.818693e+11,2.526069e+12,2.608061e+15,-6.692624e+09,-4.094099e+13,-1.675118e+09,0.0,0.0,0.0,0.0,8
1,0.2,-7.502907e+10,-5.500223e+07,1.154204e+11,5.581750e+12,2.158485e+15,-1.064073e+10,-8.097001e+12,-2.587148e+09,0.0,0.0,0.0,0.0,8
2,0.4,-8.852978e+10,-2.877874e+07,3.328066e+11,1.444057e+12,3.466406e+15,6.462528e+09,-4.868059e+13,-1.047355e+09,0.0,0.0,0.0,0.0,8
3,0.6,-9.159094e+10,-3.965101e+07,-9.764858e+10,3.706723e+12,7.004260e+15,7.050973e+09,-7.940836e+13,-2.718113e+09,0.0,0.0,0.0,0.0,8
4,0.8,-8.323025e+10,-7.355947e+07,-7.661304e+10,1.598462e+12,5.223380e+14,-9.579989e+09,3.952987e+12,-3.452363e+09,0.0,0.0,0.0,0.0,8

In [15]:
print("Rows:", len(combined_df))
print("Columns:", len(combined_df.columns))

print("\nColumns:")
print(combined_df.columns.tolist())

print("\nMissing values:")
display(combined_df.isna().sum())

print("\nDuplicate rows:")
print(combined_df.duplicated().sum())

Rows: 227039
Columns: 14

Columns:
['times(seconds)', 'bz', 'vz', 'sz', 'dL', 'dH', 'vz_dL_pos', 'vz_dH_pos', 'vzbz', 'flare6hr', 'flare12hr', 'flare24hr', 'flare48hr', 'ar_id']

Missing values:

times(seconds)       0
bz                4153
vz                4153
sz                4153
dL                4153
dH                4153
vz_dL_pos         4153
vz_dH_pos         4153
vzbz              4153
flare6hr             0
flare12hr            0
flare24hr            0
flare48hr            0
ar_id                0
dtype: int64

Duplicate rows:
0